### ISSUE TITLE
X Button Under Nav on Wide Resolution

### ISSUE THREAD

**Issue by RyanPearceN01366544** [PaulPableoSectionC/final_project_sectionC#25]
![image](https://github.com/PaulPableoSectionC/final_project_sectionC/assets/156844535/16547821-4c44-4741-91e9-56903682f546)

Currently, there is a bug with widescreen that moves the button to get out of the gallery right under the nav. You can press it right under the nav but I want to try to make it so the X button is always under the navigation. I'm going to try to add to the script to move the cancel button on the nav or perhaps moves on lightbox-div to make it always appear below it.

For now, I'm going to try to focus on the scheduling website while I can.

**Comment by PaulPableoSectionC** [comment]
@RyanPearceSectionC closing this issue as i've seen you added the fix in your last push
